version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
    expose:
      - 8080
  db:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "admin"
      # You can use whatever password you like
      MYSQL_PASSWORD: "password"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - database:/var/lib/mysql
volumes:
  database:
